---
title: "Map China With AmCharts and R"
author: "Zhenxing Cheng"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Map China With AmCharts and R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Installation

```{r eval=FALSE, include=TRUE}
devtools::install_github('czxa/mapbrew', build_vignettes = TRUE)
```

## China map

Load sample data:

```{r}
dir <- tempdir()
download.file('https://czxb.github.io/br/chinadf.rda', file.path(dir, 'chinadf.rda'))
load(file.path(dir, 'chinadf.rda'), verbose = TRUE)
```

```{r}
library(mapbrew)
library(magrittr)
df <- chinadf %>% 
  dplyr::filter(region == "China")
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0, 
      theme = "dark",
      width = "100%")
```

### Themes

The default theme:

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0,
      width = "100%")
```

light: 

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0,
      width = "100%",
      theme = "light")
```

chalk: 

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0,
      width = "100%",
      theme = "chalk")
```

dark: 

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0,
      width = "100%",
      theme = "dark")
```

black: 

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0,
      width = "100%",
      theme = "black")
```

### colorSteps: set the number of layers of colors in legends

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0,
      width = "100%",
      colorSteps = 5)
```

### smallMap: add a minimap

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 1,
      smallMapTop = 160,
      smallMapRight = 10,
      width = "100%",
      colorSteps = 5)
```

### valueLegendBottom / valueLegendRight: location of legends

```{r}
cnmap(id = df$name, 
      value = df$value, 
      description = paste0(df$name, ": ", df$value, "units"),
      smallMap = 0,
      valueLegendBottom = 40,
      valueLegendRight = 350,
      width = "100%",
      colorSteps = 5)
```

## Else

```r 
?mapbrew::cnmap()
```
